### ISSUE TITLE
Linter : Browse support ?

### ISSUE THREAD

**Issue by jy95** [alevalv/oz-vscode#5]
Hello alevalv,

Nice extension but do you think the linter could support Browser procedure (introduced in Mozart 2.0) ?
For example : 

```oz
declare
proc {Pairs L E}
    case L of nil then skip
    [] H|T then
        {Browse pair(H E)}
        {Pairs T E}
    end
end

{ForAllTail [a b c d] proc {$ Tail} {Pairs Tail.2 Tail.1} end}
```

gives : 
```
Mozart Compiler 2.0.0-alpha.0+build.4105.5c06ced (Tue, 2 Sep 2014 18:39:07 +0200) playing Oz 3

%%% feeding file c:\Users\jy95\Desktop\oztest\S2\Ex2.oz

%********************* binding analysis error *******************
%**
%** variable Browse not introduced
%**
%** in file "c:/Users/jy95/Desktop/oztest/S2/Ex2.oz", line 15, column 2
%** ------------------ rejected (1 error)

Watching build tasks has finished.
```

**Comment by alevalv** [comment]
I'm not sure what is the issue here, I have added the code that you share there and I see the error with the linter:
![image](https://user-images.githubusercontent.com/660547/36646463-9d05fa3c-1a45-11e8-81a0-01afb318b1a5.png)

I think you are missing the import to use Browse, this extension compiles the code and executes them as it is, while the mozart editor adds some stuff and then executes the code present in the editor.

If you want to use `{Browse ...}` with this extension then you need to modify your source similar to this (be aware that if you use it the process that is launched to run the application will still run even after closing the Browser window, vscode will let you know that is running and give you the choice to kill it if you launch it again):

```oz
functor
import
    Browser(browse:Browse)
define Wa
    proc {Pairs L E}
        case L of nil then skip
            [] H|T then
            {Browse pair(H E)}
            {Pairs T E}
        end
    end

    {ForAllTail [a b c d] proc {$ Tail} {Pairs Tail.2 Tail.1} end}
end
```

Also, you can use the System module to print to console, you can check that [here](https://mozart.github.io/mozart-v1/doc-1.4.0/system/node80.html).

This is how the Mozart compiler works, and that is what this extension uses to run the code. There will no parity with the current Mozart editor, at least not by me, that is a huge task.

I'll update the README to show this example so people know what to use when using the extension.

**Comment by jy95** [comment]
Thanks for the answer : The mozart compiler doesn't seem to handle your sample ^^
Mozart 2.0 brokes a lot of things : for example the `functor` keywork is replaced by `fun` (undocumented stuff like always in mozart).

**Comment by alevalv** [comment]
I tested that code with `Mozart Compiler 2.0.0-alpha.0+build.4140.005f700 (Sun, 22 Mar 2015 00:16:52 +0800) playing Oz 3`, which is the most recent build, compiled it with `ozc -c filename` and it works. Could you try with that build?

**Comment by jy95** [comment]
Oh sorry, I think It was because VSCode had another open file tab.
Effectively , it works in the terminal , the compilation with `Mozart Compiler 2.0.0-alpha.0+build.4105.5c06ced (Tue, 2 Sep 2014 18:39:07 +0200) playing Oz 3` works and with the VScode `build` task .
